/* SPDX-License-Identifier: CC0-1.0
 * SPDX-FileCopyrightText: 2026 RVLab Student Project
 *
 * Generated by tools/export_dav2.py -- do not edit.
 * Regenerate by re-running the exporter with the desired --size.
 */
#ifndef DAV2_BLOB_CONFIG_H
#define DAV2_BLOB_CONFIG_H

#define DAV2_INPUT_SIZE   126
#define DAV2_PATCH_GRID   9
#define DAV2_N_TOKENS     82
#define DAV2_N_PATCHES    81
#define DAV2_BLOB_BYTES   24871428u

#endif
